module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  administration_language_negotiation: 0
  auto_entitylabel: 0
  auto_user_role: 0
  automated_cron: 0
  betterlogin: 0
  bid: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  cargaview: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  entity: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flete_profiles: 0
  flete_route: 0
  geocoder_autocomplete: 0
  help: 0
  hide_revision_field: 0
  history: 0
  image: 0
  language: 0
  layout_discovery: 0
  link: 0
  locale: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  path: 0
  profile: 0
  quickedit: 0
  rdf: 0
  route_planner: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  flete: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
