country:
  default: CR
first_day: 1
timezone:
  default: America/Costa_Rica
  user:
    configurable: true
    warn: false
    default: 1
_core:
  default_config_hash: V9UurX2GPT05NWKG9f2GWQqFG2TRG8vczidwjpy7Woo
langcode: es
